### PR TITLE
Preparing 2.2.0 release

### PR DESCRIPTION
**Pull request by vincent-fuchs**

### CODE REVIEW

**Comment by vincent-fuchs** [comment]
@chandrasekharpanigrahy can you please review the simple doc I added for Bitbucket ?

I am not familiar with Bitbucket concepts.. is there really a need for both organizationName and project-name properties in the config ? in the tests, you've given it the same value.. so should it be only one value ?

**Comment by chandrasekharpanigrahy** [comment]
> @chandrasekharpanigrahy can you please review the simple doc I added for Bitbucket ?
> 
> I am not familiar with Bitbucket concepts.. is there really a need for both organizationName and project-name properties in the config ? in the tests, you've given it the same value.. so should it be only one value ?

Thank you @vincent-fuchs . missed to clean this, soon will raising PR to remove.

**Comment by chandrasekharpanigrahy** [comment]
https://github.com/societe-generale/github-crawler/pull/119

**Comment by vincent-fuchs** [comment]
Thanks @chandrasekharpanigrahy , I will merge this soon and make a release right after

**Pull request merged**
